spring:
  application:
    name: meetingmanagementproject
  security:
    user:
      name: taeyun1118
      password: taeyun30504
  datasource:
    url: jdbc:mysql://localhost:3307/swaggerdb
    username: taeyun
    password: gwon
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
